<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['site'] = array(
    'auth_code'         => 'a0b450c8ad7dea49a486ea96de431a9e',
    'cache_time'         => '0',
    'comment_code'         => '',
    'count_code'         => '',
    'data_center_url'         => 'http://www.711cms.com/api',
    'pagesize'         => '20',
    'version'         => '1.0.0',
    'update_time'         => '1499330434',
    'static_url'         => 'static',
    'is_site_rewrite'         => '-1',
    'is_content_mobile'         => '1',
    'is_images_local'         => '',
    'is_images_rewrite'         => '',
    'is_content_nlink'         => '',
    'seo_description'         => '711cms',
    'seo_keywords'         => '711cms',
    'seo_title'         => '711cms',
    'site_logo'         => '/uploads/images/9604a4f67391f4dc1010dce413c373ac.png',
    'site_name'         => '711cms网站名称',
    'site_safe_code'         => '123456',
    'site_url'         => 'http://cms.711cms.com',
    'site_beian'         => '',
    'site_copyright'         => '',
    'site_path'         => '/',
    'template'         => 'template_001',
    'upload_key'         => 'b7fc8d93e2e97290a9e0a096502ed1b6',
    'upload_path'         => '/uploads/images/',
    'upload_path_apk'         => '/uploads/apk/',
    'wap_logo'         => '/uploads/images/9604a4f67391f4dc1010dce413c373ac.png',
    'wap_url'         => 'http://cms.711cms.com',
    'wap_seo_description'         => '711cms',
    'wap_seo_keywords'         => '711cms',
    'wap_seo_title'         => '711cms',
    'wap_template'         => 'template_1',
);
